### ISSUE TITLE
[PE-D][Tester C] Window Resizing Limitation

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T16-1/tp#126]
![FF - unable to make window smaller.png](https://raw.githubusercontent.com/sebin0817/ped/main/files/16e3370d-8ead-492a-9f94-acd3e9cfc20c.png)

Details: Unable to resize the application window below a certain threshold, limiting usability on smaller screens. Expected more flexibility in window sizing.

Suggestion: Adjust the minimum window size constraints to enhance compatibility with various screen sizes.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: sebin0817/ped#7

**Comment by Austintjh19** [comment]
Resolved.
