### ISSUE TITLE
[PE-D][Tester B] Requirement to click on command line to execute previous command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T16-1/tp#143]
When using the GUI to click on a previous command to re-execute it, one has to click on the command (as marked in `Accessing the Recent Commands in CommandBox`) and then click on the command box to execute it.

Depending on intent, this could be considered a feature flaw.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: TopKec/ped#5

**Comment by dedsecrattle** [comment]
Fixed
