### ISSUE TITLE
[PE-D][Tester D] View command is not optimised for CLI

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T16-1/tp#161]
To view a student card, the user has the left-click on the person on the list. There is no equivalent CLI-based command to view the student card. This might make the app difficult for someone who does not have access to a mouse/ trackpad to interact with the app.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: teojunda/ped#16

**Comment by dedsecrattle** [comment]
Finished
